### ISSUE TITLE
Receive data from clients

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Sylver#2]
## Description
The `NetServer` should start receiving data after the client has been accepted by the `NetServerAcceptor`.
It should handle both `raw` (simple text) or `packed` (packet) data depending on the server's configuration.

## Roadmap

- [ ] Start receiving data
- [ ] Handle TCP message framing
- [ ] Handle `raw` and `packed` data
- [ ] Call correct client data handler
