### ISSUE TITLE
Packet stream

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Sylver#3]
## Description
A packet stream represents a stream of packed data. This stream is buffered and contains the data that will be sent to the client or server.
The packet stream should have methods to `Read()` and `Write()` primitive data. (ex: `int`, `byte`, `short`, ect...)

Also, we could have the possibility to register other types that could inherit from an interface and force to implement the serialization and deserialization process. This process could be called: `NetPacketSerializer`

### Suggested names
There are some suggested names for the implementation of the packet stream feature:

| Suggested name | Description |
|-------------------|------------|
| `INetPacketStream` | Packet stream interface |
| `NetPacketStream` | Provides a mechanism to read and write into a packet stream |
| `NetPacket` | Inherits from `NetPacketStream` and provides a default built-in packet implementation |
| `INetPacketProcessor` | Provides a mechanism to customize the parsing of the packet data during the receiving process. |
| `INetPacketSerializer` | Provides an interface that specifies the serialization and deserialization process of a complex object. |

## Roadmap

- [ ] Create the `NetPacketStream` implementation.
- [ ] Create the `NetPacket` implementation.
- [ ] Create the `INetPacketProcessor` and the default `NetPacketProcessor` implementation.
- [ ] Create documentation about the `NetPacketStream` and `NetPacket` behavior.
- [ ] Create documentation about the `INetPacketProcessor` behavior.

## VNext

- [ ] Create the `INetPacketSerializer`

**Comment by KSExtrez** [comment]
Hi,
I think that is good idea add skip or ignore bytes from packets

**Comment by Eastrall** [comment]
Hi @KSExtrez, Thank you for the suggestion. 
It can be interesting to add such method to skip bytes into the packet instead of using the `Position` property of the `MemoryStream`.
We could have: `INetPacketStream.Skip(int bytesCount)` that will internally increment the `MemoryStream.Position` property with the `bytesCount` value.

**Comment by Eastrall** [comment]
@KSExtrez commit e49a656dd222c01585f204caccb3fee1e6626ef2 adds the `INetPacketStream.Skip(int byteCount)` method that skips a given number of bytes.
See unit test [here](https://github.com/Eastrall/Sylver/commit/e49a656dd222c01585f204caccb3fee1e6626ef2#diff-8e1fce16240807db892c3ff996e8f732R98) to see how it works.

**Comment by KSExtrez** [comment]
Hi, 
I would like more information about PacketSerialize, this interface should convert an object to byte array?
If It's true, we can use Marshal for serialize the objetc attributes?
