### ISSUE TITLE
Send data to one or more clients

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Sylver#4]
## Description

When users are connected and send data to the server, depending on the program workflow, sometimes, the server needs to send data back to the client.
To increase flexibility, the `INetServer` server interface will need to have 3 methods. One for sending a message to one connected user, another method to send a message to a collection of connected users and finally, a method to send a message to everyone.
Of course, a `INetClient` will also have a send method that will call the server's methods. It would be *just* an alias

### Suggested method names

The are the suggested names for the sending methods:

#### `INetServer`

| Suggested name | Parameters | Description |
|--------------------|-------------|--------------|
| `SendMessageTo` | `INetUser user`, `byte[] message` | Sends a message to a single user. |
| `SendMessageTo` | `IEnumerable<INetUser> users`, `byte[] message` | Sends a message to a collection of users.  |
| `SendMessageToAll` | `byte[] message` | Sends a message to every connected users.  |

#### `INetUser`

| Suggested name | Parameters | Description |
|--------------------|-------------|--------------|
| `SendPacket` | `INetPacketStream packet` | Calls `INetServer.SendMessageTo(this, packet.Buffer)` where this is the current `INetUser` instance. |
| `SendPacketTo` | `INetUser user`, `INetPacketStream packet` | Calls `INetServer.SendMessageTo(user, packet.Buffer)` |
| `SendPacketTo` | `IEnumerable<INetUser> users`, `INetPacketStream packet` | Calls `INetServer.SendMessageTo(users, packet.Buffer)`  |
| `SendPacketToAll` | `INetPacketStream packet` | Calls `INetServer.SendMessageToAll(packet.Buffer)` |

## Roadmap

- [x] Add a `INetServer` reference to `INetServerClient`. *This will allow the users to access their parent server.* (24accc46f8bda248b346d32dfc34430e31ea0943)
- [x] Server can send data to one or more clients. (24accc46f8bda248b346d32dfc34430e31ea0943)
- [x] `INetUser`s can send data to them selfs or other connected clients. (24accc46f8bda248b346d32dfc34430e31ea0943)
- [x] Process sending queue (24accc46f8bda248b346d32dfc34430e31ea0943)

**Comment by carlst99** [comment]
I think the suggested names sound good. However, I wonder if it would be less confusing to rename the ```SendMessage``` method of ```INetUser``` that sends a message to the current instance. Perhaps something like ```SendMessageToSelf```? This makes more sense in my opinion, as all the other methods are sending data to a client other than themselves.

**Comment by Eastrall** [comment]
Thank you for sharing your opinion @carlst99. I don't really know how to feel about the `*Self()` methods. Usualy, when you want to make a process on the current object, you don't really need to specify the `*Self()` since you are actually inside the current object.

Maybe, just keeping the `INetUser.SendMessage()` to send a message to the current user, and keep other methods like: `INetUser.SendMessageTo(INetUser, byte[])` and `INetUser.SendMessageTo(IEnumerable<INetUser>, byte[])` ?

We will be using it like:

```csharp
{
   ...
   user.SendMessage(...);
}
```

Doing something like:
```csharp
{
   ...
   user.SendMessageToSelf(...);
}
```
might be a little redundant ?

Does that make sense to you?

**Comment by Eastrall** [comment]
As discussed in issue #5, I have renamed the `*NetUser` into `*NetServerClient`.
I tought that the `INetServer` should have a `SendMessageTo(user | users)` method instead of `SendMessage(user | users)` because when you write the code, you understand directly by reading these lines, that you are sending a message TO a specific client:

```csharp
INetServer myServer = ... // we asume that we have a running server instance.
INetServerClient eastrallClient = ... // We retrieve somehow the NetServerClient of "eastrall"

myServer.SendMessageTo(eastrallClient, new byte[] { 8, 0, 0, 0, 0, .... });
```

As for the `NetServerClient` itself, it will still have the `SendMessageTo(user | users, data)` and will have a `SendMessage(byte[])` to send the the message data to it self by calling the following method:
```csharp
public void SendMessage(byte[] messageData) => this._server.SendMessageTo(this, messageData);
```
What do ou think about it ?

**Comment by carlst99** [comment]
I think that's great!
