### ISSUE TITLE
NetClient implementation

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Sylver#7]
## Description

The `NetClient` is managed TCP client. It provides the possibility to connect to a `NetServer` or any other kind of TCP servers, send and receive packets using a `NetPacketStream`.

## Roadmap

- [ ] Create the `NetClientConfiguration`
- [ ] Create the `INetClient` interface and `NetClient` implementation
- [ ] Connect to a `NetServer` with retry
- [ ] Send packets
- [ ] Receive packets
- [ ] Disconnects from a server
- [ ] Retry connection when connection lost
